pool:
  vmImage: 'windows-2019'
    
variables:
- group: 'github-config'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
- task: PowerShell@2
  displayName: Install MkDocs
  inputs:
    targetType: 'inline'
    script: |
      pip install mkdocs mkdocs-material mkdocs-minify-plugin --disable-pip-version-check
    failOnStderr: false
    workingDirectory: '$(Build.SourcesDirectory)'
- task: PowerShell@2
  displayName: Build with MkDocs
  inputs:
    targetType: 'inline'
    script: |
      mkdocs build -q
    failOnStderr: true
    workingDirectory: '$(Build.SourcesDirectory)'
- task: ArchiveFiles@2
  displayName: 'Create Zip archive'
  inputs:
    rootFolderOrFile: 'site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Zip archive'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: PowerShell@2
  displayName: 'Push to GitHub'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    targetType: 'inline'
    script: |
      git remote add github https://$(PAT)@github.com/stuebersystems/doc.quattropod.en.git
      git fetch github
      git checkout .
      git push github HEAD:main
      git push --tags github HEAD:main
    pwsh: true  
