# Project information
site_name: QuattroPod Documentation
site_url: 'https://doc.quattropod.eu'
site_author: 'STÜBER SYSTEMS GmbH'
site_description: >-
    Our documentation for all QuattroPod products.  

# Repository
repo_name: 'On GitHub'
repo_url: 'https://github.com/stuebersystems/doc.quattropod.en'

# Copyright
copyright: '&copy; 2021 STÜBER SYSTEMS GmbH'

# Configuration
theme:
    name: material
    custom_dir: overrides
    static_templates:
        - 404.html
    include_search_page: false
    search_index_only: true
    language: de
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        scheme: default
    favicon: assets/img/favicon.ico
    logo: assets/img/logo.svg
    font: false

# Legal links
extra:
    legal:
        - label: Imprint
          link: https://www.stueber.co.uk/imprint.php
        - label: Privacy
          link: https://legal.stueber.co.uk/privacy.php

# Customization
extra_css:
    - assets/css/custom.css

# Plugins
plugins:
    - search
    - minify:
        minify_html: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

# Page tree
nav:
- Überblick: 
    - Einführung: index.md
    - Was ist neu?: whatsnew.md
    - Anschlüsse: ports.md
    - Datensicherheit: datasecurity.md
    - Firmware aktualisieren: firmware-upgrade.md
- QuattroPod USB:
    - Überblick: usb/intro.md
    - Schnellstartanleitung: usb/quickstart.md
    - Was ist neu?: usb/whatsnew.md
    - Anleitungen nach<br>Betriebssystem:
        - "Anleitung: Android": usb/quickstart/#android
        - "Anleitung: iOS": usb/quickstart/#ios
        - "Anleitung: macOS": usb/quickstart/#windows-macos
        - "Anleitung: Linux": usb/linux.md
        - "Anleitung: Windows": usb/quickstart/#windows-macos
    - Anleitungen nach<br>Streamingprotokoll:
        - "Anleitung: AirPlay": usb/airplay.md     
        - "Anleitung: Chromecast": usb/chromecast.md
    - Internetzugang: usb/internet.md
    - Erweiterte Funktionen:
        - Erweiterte Einstellungen: usb/adv.settings.md
        - Konferenzsteuerung: usb/conference-control.md
        - Monitor-Modus: usb/monitor-setup.md 
        - Remote-Verwaltung: usb/remote-management.md
        - Sender koppeln: usb/pairing.md
        - Touch-Back-Funktion: usb/touchback.md
        - Captive Portal: usb/captiveportal.md
    - Firmware aktualisieren: usb/firmware-upgrade.md
    - Problembehandlung:
        - Einstellungen zurücksetzen: usb/reset.md
        - Firmware neu installieren: usb/firmware-reinstall.md
    - CMS: usb/cms.md    
- QuattroPod Lite:
    - Überblick: lite/intro.md
    - Schnellstartanleitung: lite/quickstart.md
    - Was ist neu?: lite/whatsnew.md
    - Anleitungen nach<br>Betriebssystem:
        - "Anleitung: Android": lite/quickstart/#android
        - "Anleitung: iOS": lite/quickstart/#ios
        - "Anleitung: macOS": lite/quickstart/#windows-macos-linux
        - "Anleitung: Linux": lite/linux.md
        - "Anleitung: Windows": lite/quickstart/#windows-macos-linux
    - Anleitungen nach<br>Streamingprotokoll:
        - "Anleitung: AirPlay": lite/airplay.md     
        - "Anleitung: Chromecast": lite/chromecast.md
    - Internetzugang: lite/internet.md
    - Erweiterte Funktionen:
        - Captive Portal: lite/captiveportal.md
        - Dynamisches Hintergrundbild: lite/dynamicwallpaper.md
        - Erweiterte Einstellungen: lite/adv.settings.md
        - Konferenzsteuerung: lite/conference-control.md
        - Monitor-Modus: lite/monitor-setup.md 
        - Remote-Verwaltung: lite/remote-management.md
        - Sender koppeln: lite/pairing.md
        - Touch-Back-Funktion: lite/touchback.md
    - Firmware aktualisieren: lite/firmware-upgrade.md
    - Problembehandlung:
        - Einstellungen zurücksetzen: lite/reset.md
        - Firmware neu installieren: lite/firmware-reinstall.md
    - CMS: lite/cms.md
- QuattroPod Mini: 
    - Überblick: mini/intro.md
    - Schnellstartanleitung: mini/quickstart.md
    - Was ist neu?: mini/whatsnew.md
    - Anleitungen nach<br>Betriebssystem:
        - "Anleitung: Android": mini/quickstart/#android
        - "Anleitung: iOS": mini/quickstart/#ios
        - "Anleitung: macOS": mini/quickstart/#windows-macos-linux
        - "Anleitung: Linux": mini/linux.md
        - "Anleitung: Windows": mini/quickstart/#windows-macos-linux
    - Anleitungen nach<br>Streamingprotokoll:
        - "Anleitung: AirPlay": mini/airplay.md     
        - "Anleitung: Chromecast": mini/chromecast.md
    - Internetzugang: mini/internet.md
    - Erweiterte Funktionen: 
        - Captive Portal: mini/captiveportal.md
        - Dynamisches Hintergrundbild: mini/dynamicwallpaper.md
        - Erweiterte Einstellungen: mini/adv.settings.md
        - Festgelegter Host: mini/fixedhost.md
        - Konferenzsteuerung: mini/conference-control.md
        - Monitor-Modus: mini/monitor-setup.md 
        - Multicast: mini/multicast.md
        - Remote-Verwaltung: mini/remote-management.md
        - Sender bedienen: mini/TX-controls.md
        - Sender koppeln: mini/pairing.md
        - Touch-Back-Funktion: mini/touchback.md
    - Firmware aktualisieren: mini/firmware-upgrade.md
    - Problembehandlung: 
        - Einstellungen zurücksetzen: mini/reset.md
        - Firmware neu installieren: mini/firmware-reinstall.md
    - CMS: mini/cms.md
- QuattroPod Standard: 
    - Überblick: standard/intro.md
    - Schnellstartanleitung: standard/quickstart.md
    - Was ist neu?: standard/whatsnew.md
    - Anleitungen nach<br>Betriebssystem:
        - "Anleitung: Android": standard/quickstart/#android
        - "Anleitung: iOS": standard/quickstart/#ios
        - "Anleitung: macOS": standard/quickstart/#windows-macos-linux
        - "Anleitung: Linux": standard/linux.md
        - "Anleitung: Windows": standard/quickstart/#windows-macos-linux
    - Anleitungen nach<br>Streamingprotokoll:
        - "Anleitung: AirPlay": standard/airplay.md     
        - "Anleitung: Chromecast": standard/chromecast.md
    - Internetzugang: standard/internet.md
    - Erweiterte Funktionen:
        - Captive Portal: standard/captiveportal.md
        - Dynamisches Hintergrundbild: standard/dynamicwallpaper.md
        - Erweiterte Einstellungen: standard/adv.settings.md
        - Festgelegter Host: standard/fixedhost.md
        - Konferenzsteuerung: standard/conference-control.md
        - Monitor-Modus: standard/monitor-setup.md
        - Multicast: standard/multicast.md
        - Remote-Verwaltung: standard/remote-management.md
        - Sender bedienen: standard/TX-controls.md
        - Sender koppeln: standard/pairing.md
        - Touch-Back-Funktion: standard/touchback.md
    - Firmware aktualisieren: standard/firmware-upgrade.md
    - Problembehandlung: 
        - Einstellungen zurücksetzen: standard/reset.md
        - Firmware neu installieren: standard/firmware-reinstall.md
    - CMS: standard/cms.md
- QuattroPod Deluxe:
    - Überblick: deluxe/intro.md
    - Schnellstartanleitung: deluxe/quickstart.md
    - Was ist neu?: deluxe/whatsnew.md
    - Anleitungen nach<br>Betriebssystem:
        - "Anleitung: Android": deluxe/quickstart/#android
        - "Anleitung: iOS": deluxe/quickstart/#ios
        - "Anleitung: macOS": deluxe/quickstart/#windows-macos-linux
        - "Anleitung: Linux": deluxe/linux.md
        - "Anleitung: Windows": deluxe/quickstart/#windows-macos-linux
    - Anleitungen nach<br>Streamingprotokoll:
        - "Anleitung: AirPlay": deluxe/airplay.md     
        - "Anleitung: Chromecast": deluxe/chromecast.md
    - Internetzugang: deluxe/internet.md
    - Erweiterte Funktionen:
        - Captive Portal: deluxe/captiveportal.md    
        - Dynamisches Hintergrundbild: deluxe/dynamicwallpaper.md
        - Erweiterte Einstellungen: deluxe/adv.settings.md
        - Festgelegter Host: deluxe/fixedhost.md
        - Konferenzsteuerung: deluxe/conference-control.md
        - Monitor-Modus: deluxe/monitor-setup.md
        - Multicast: deluxe/multicast.md
        - Remote-Verwaltung: deluxe/remote-management.md
        - Sender bedienen: deluxe/TX-controls.md
        - Sender koppeln: deluxe/pairing.md
        - Touch-Back-Funktion: deluxe/touchback.md
    - Firmware aktualisieren: deluxe/firmware-upgrade.md
    - Problembehandlung: 
        - Einstellungen zurücksetzen: deluxe/reset.md
        - Firmware neu installieren: deluxe/firmware-reinstall.md
    - CMS: deluxe/cms.md
