# Project information
site_name: QuattroPod Documentation
site_url: 'https://doc.quattropod.eu'
site_author: 'STÜBER SYSTEMS GmbH'
site_description: >-
    Our documentation for all QuattroPod products.  

# Repository
repo_name: 'On GitHub'
repo_url: 'https://github.com/stuebersystems/doc.quattropod.en'

# Copyright
copyright: '&copy; 2021 STÜBER SYSTEMS GmbH'

# Configuration
theme:
    name: material
    custom_dir: overrides
    static_templates:
        - 404.html
    include_search_page: false
    search_index_only: true
    language: de
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        scheme: default
    favicon: assets/img/favicon.ico
    logo: assets/img/logo.svg
    font: false

# Legal links
extra:
    legal:
        - label: Imprint
          link: https://www.stueber.co.uk/imprint.php
        - label: Privacy
          link: https://legal.stueber.co.uk/privacy.php

# Customization
extra_css:
    - assets/css/custom.css

# Plugins
plugins:
    - search
    - minify:
        minify_html: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols

# Page tree
nav:
- Overview: 
    - Introduction: index.md
    - What's New?: whatsnew.md
    - Ports: ports.md
    - Data Security: datasecurity.md
    - Upgrade Firmware: firmware-upgrade.md
- USB:
    - Introduction: usb/intro.md
    - Quick Start Guide: usb/quickstart.md
    - What's New?: usb/whatsnew.md
    - User Guides by<br>Operating System:
        - "User Guide: Android": usb/quickstart/#android
        - "User Guide: iOS": usb/quickstart/#ios
        - "User Guide: macOS": usb/quickstart/#windows-macos
        - "User Guide: Linux": usb/linux.md
        - "User Guide: Windows": usb/quickstart/#windows-macos
    - User Guides by<br>Streaming Protocol:
        - "User Guide: AirPlay": usb/airplay.md     
        - "User Guide: Chromecast": usb/chromecast.md
    - Internet Access: usb/internet.md
    - Advanced Features:
        - Advanced Settings: usb/adv.settings.md
        - Captive Portal: usb/captiveportal.md
        - Conference Control: usb/conference-control.md
        - Display Modes: usb/monitor-setup.md
        - Dynamic Wallpaper: usb/dynamicwallpaper.md
        - Fixed Host: usb/fixedhost.md
        - Multicast: usb/multicast.md
        - Remote Management: usb/remote-management.md
        - Transmitter Operation: usb/TX-controls.md
        - Transmitter Pairing: usb/pairing.md
        - Touch Back Function: usb/touchback.md
    - Update Firmware: usb/firmware-upgrade.md
    - Troubleshooting:
        - Reset Settings: usb/reset.md
        - Reinstall Firmware: usb/firmware-reinstall.md
        - Captive Portal: usb/captiveportal.md
    - CMS: usb/cms.md    
- Lite:
    - Introduction: lite/intro.md
    - Quick Start Guide: lite/quickstart.md
    - What's New?: lite/whatsnew.md
    - User Guides by<br>Operating System:
        - "User Guide: Android": lite/quickstart/#android
        - "User Guide: iOS": lite/quickstart/#ios
        - "User Guide: macOS": lite/quickstart/#windows-macos-linux
        - "User Guide: Linux": lite/linux.md
        - "User Guide: Windows": lite/quickstart/#windows-macos-linux
    - User Guides by<br>Streaming Protocol:
        - "User Guide: AirPlay": lite/airplay.md     
        - "User Guide: Chromecast": lite/chromecast.md
    - Internet Access: lite/internet.md
    - Advanced Features:
        - Captive Portal: lite/captiveportal.md
        - Dynamic Wallpaper: lite/dynamicwallpaper.md
        - Advanced Settings: lite/adv.settings.md
        - Conference Control: lite/conference-control.md
        - Display Mode: lite/monitor-setup.md 
        - Remote Management: lite/remote-management.md
        - Transmitter Pairing: lite/pairing.md
        - Touch Back Function: lite/touchback.md
    - Update Firmware: lite/firmware-upgrade.md
    - Troubleshooting:
        - Reset Settings: lite/reset.md
        - Reinstall Firmware: lite/firmware-reinstall.md
    - CMS: lite/cms.md
- Mini: 
    - Introduction: mini/intro.md
    - Quick Start Guide: mini/quickstart.md
    - What's New?: mini/whatsnew.md
    - User Guides by<br>Operating System:
        - "User Guide: Android": mini/quickstart/#android
        - "User Guide: iOS": mini/quickstart/#ios
        - "User Guide: macOS": mini/quickstart/#windows-macos-linux
        - "User Guide: Linux": mini/linux.md
        - "User Guide: Windows": mini/quickstart/#windows-macos-linux
    - User Guides by<br>Streaming Protocol:
        - "User Guide: AirPlay": mini/airplay.md     
        - "User Guide: Chromecast": mini/chromecast.md
    - Internet Access: mini/internet.md
    - Advanced Features:
        - Advanced Settings: mini/adv.settings.md
        - Captive Portal: mini/captiveportal.md
        - Conference Control: mini/conference-control.md
        - Display Modes: mini/monitor-setup.md
        - Dynamic Wallpaper: mini/dynamicwallpaper.md
        - Fixed Host: mini/fixedhost.md
        - Conference Control: mini/conference-control.md
        - Display Mode: mini/monitor-setup.md 
        - Multicast: mini/multicast.md
        - Remote Management: mini/remote-management.md
        - Transmitter Operation: mini/TX-controls.md
        - Transmitter Pairing: mini/pairing.md
        - Touch Back Function: mini/touchback.md
    - Update Firmware: mini/firmware-upgrade.md
    - Troubleshooting: 
        - Reset Settings: mini/reset.md
        - Reinstall Firmware: mini/firmware-reinstall.md
    - CMS: mini/cms.md
- Standard: 
    - Introduction: standard/intro.md
    - Quick Start Guide: standard/quickstart.md
    - What's New?: standard/whatsnew.md
    - User Guides by<br>Operating System:
        - "User Guide: Android": standard/quickstart/#android
        - "User Guide: iOS": standard/quickstart/#ios
        - "User Guide: macOS": standard/quickstart/#windows-macos-linux
        - "User Guide: Linux": standard/linux.md
        - "User Guide: Windows": standard/quickstart/#windows-macos-linux
    - User Guides by<br>Streaming Protocol:
        - "User Guide: AirPlay": standard/airplay.md     
        - "User Guide: Chromecast": standard/chromecast.md
    - Internet Access: standard/internet.md
    - Advanced Features:
        - Advanced Settings: standard/adv.settings.md
        - Captive Portal: standard/captiveportal.md
        - Conference Control: standard/conference-control.md
        - Display Modes: standard/monitor-setup.md
        - Dynamic Wallpaper: standard/dynamicwallpaper.md
        - Fixed Host: standard/fixedhost.md
        - Display Mode: standard/monitor-setup.md
        - Multicast: standard/multicast.md
        - Remote Management: standard/remote-management.md
        - Transmitter Operation: standard/TX-controls.md
        - Transmitter Pairing: standard/pairing.md
        - Touch Back Function: standard/touchback.md
    - Update Firmware: standard/firmware-upgrade.md
    - Troubleshooting: 
        - Reset Settings: standard/reset.md
        - Reinstall Firmware: standard/firmware-reinstall.md
    - CMS: standard/cms.md
- Deluxe:
    - Introduction: deluxe/intro.md
    - Quick Start Guide: deluxe/quickstart.md
    - What's New?: deluxe/whatsnew.md
    - User Guides by<br>Operating System:
        - "User Guide: Android": deluxe/quickstart/#android
        - "User Guide: iOS": deluxe/quickstart/#ios
        - "User Guide: macOS": deluxe/quickstart/#windows-macos-linux
        - "User Guide: Linux": deluxe/linux.md
        - "User Guide: Windows": deluxe/quickstart/#windows-macos-linux
    - User Guides by<br>Streaming Protocol:
        - "User Guide: AirPlay": deluxe/airplay.md     
        - "User Guide: Chromecast": deluxe/chromecast.md
    - Internet Access: deluxe/internet.md
    - Advanced Features:
        - Advanced Settings: deluxe/adv.settings.md
        - Captive Portal: deluxe/captiveportal.md
        - Conference Control: deluxe/conference-control.md
        - Display Modes: deluxe/monitor-setup.md
        - Dynamic Wallpaper: deluxe/dynamicwallpaper.md
        - Fixed Host: deluxe/fixedhost.md
        - Display Mode: deluxe/monitor-setup.md
        - Multicast: deluxe/multicast.md
        - Remote Management: deluxe/remote-management.md
        - Transmitter Operation: deluxe/TX-controls.md
        - Transmitter Pairing: deluxe/pairing.md
        - Touch Back Function: deluxe/touchback.md
        - Update Firmware: deluxe/firmware-upgrade.md
    - Troubleshooting: 
        - Reset Settings: deluxe/reset.md
        - Reinstall Firmware: deluxe/firmware-reinstall.md
    - CMS: deluxe/cms.md
- CMS: 
    - Introduction: cms.md  